import customtkinter as ctk

ctk.set_appearance_mode("dark")
ctk.set_default_color_theme("green")

# Window

WINDOW_TITLE = "Verioke"
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
MIN_WIDTH = 1000
MIN_HEIGHT = 600

# Fonts

FONT_FAMILY = "Comic Sans MS"
TITLE_FONT = (FONT_FAMILY, 42, "bold")
HEADING_FONT = (FONT_FAMILY, 30, "bold")
BODY_FONT = (FONT_FAMILY, 22)
SMALL_FONT = (FONT_FAMILY, 16)

# Colors

BACKGROUND = "#101010"
PANEL = "#1B1B1B"
PRIMARY = "#21B14E"
SECONDARY = "#303030"
ACCENT = "#FFD43B"
INFO = "#3FA9F5"
TEXT = "#FFFFFF"
TEXT_SECONDARY = "#D0D0D0"
SUCCESS = "#43D66D"
WARNING = "#FFC857"
ERROR = "#FF5555"
CURRENT_LYRIC = "#2339FF"
NEXT_LYRIC = "#FFFFFF"

# Layout

CORNER_RADIUS = 15
PADDING = 15
LEFT_PANEL_WIDTH = 300
BOTTOM_BAR_HEIGHT = 70
SONG_PANEL_TITLE_TOP = 20
SONG_PANEL_TITLE_BOTTOM = 30
COVER_SIZE = 350
COVER_TOP_PADDING = 30
SONG_NAME_TOP = 20
SONG_NAME_BOTTOM = 5
DURATION_TOP = 10
DURATION_BOTTOM = 25
SING_BUTTON_WIDTH = 250
SING_BUTTON_HEIGHT = 60
BOTTOM_SIDE_PADDING = 30
BOTTOM_WAVEFORM_FONT_SIZE = 20